### ISSUE TITLE
Static file beaker-job.rng has different location after latest deployments.

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-project.org#24]
So by default, it is expected that file `beaker-job.rng` will be located under `docs/_downloads/beaker-job.rng`. For an unknown reason, there is one extra folder. So path looks like `docs/_downloads/<random_hash>/beaker-job.rng`.

This has to be corrected and location should be same as I mentioned at the beginning.

**Comment by renanrodrigo** [comment]
This is a [change](https://www.sphinx-doc.org/en/1.8/changes.html#id11) in Sphinx 1.8.0. All downloads have a hash [(doc)](https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=downloads#role-download) in the path, to support duplicate filenames.

If we really need it in the previous behavior we would need to:
a) pin Sphinx to a pre-1.8.0 version
b) move it manually after docs are generated.

Downsides are:
a) ensures obsoleteness; one option of the build script will be de-simplified for compatibility
b) painful workaround script

**Comment by StykMartin** [comment]
Pain is good. 
I would go with b if we can't tweak Sphinx opts somehow.

**Comment by renanrodrigo** [comment]
Solved in docs building script.
