### ISSUE TITLE
Expired HTTPS certificate: https://git.beaker-project.org

### ISSUE THREAD

**Issue by jankratochvil** [beaker-project/beaker-project.org#26]
Common Name: beaker-project.org
Issuer Organization: Let's Encrypt
Not After: 6/11/2020, 10:24:23 AM (Central European Summer Time)

**Comment by StykMartin** [comment]
We are not planning to renew `gerrit/git.beaker-project.org`.
We decided to use GitHub for issues/code/pull requests as maintaining Gerrit instance gave us just pain especially due to broken sync sometimes resulting to unexpected results.
