### ISSUE TITLE
Migrate hrefs to git.beaker-project.org

### ISSUE THREAD

**Issue by jankratochvil** [beaker-project/beaker-project.org#27]
[Issues 26 ](https://github.com/beaker-project/beaker-project.org/issues/26)does not want to fix HTTPS certificate for [git.beaker-project.org](http://git.beaker-project.org) but still www.beaker-project.org contains tons of links to [git.beaker-project.org](http://git.beaker-project.org). So if [git.beaker-project.org](http://git.beaker-project.org) is dead it should be (1) removed from DNS and (2) migrate all the links to github.
BTW links to http://git.beaker-project.org are still the same as https://git.beaker-project.org links as there is HTTPS Everywhere rule for beaker-project.org: https://atlas.eff.org/domains/beaker-project.org.html

**Comment by StykMartin** [comment]
Hi @duck-rh,

Can you please clear out records?
I will take a look at how many links left in latest `dev` build for website. I guess none

**Comment by jankratochvil** [comment]
There is still 26 of them:
```
$ wget -np -r https://beaker-project.org/
$ grep -ri git.beaker beaker-project.org/|grep -v ^Binary|wc -l
26
```
Although I got to broken http://git.beaker-project.org yesterday immediately from the main website while now I do not see any such obvious link so if it is fixed since yesterday great. Feel free to close the ticket but some of the links would be still worth fixing IMO.

**Comment by jankratochvil** [comment]
I think these hrefs still could be fixed, couldn't they?

https://beaker-project.org/docs/whats-new/index.html
&lt;a class="reference external" href="http://git.beaker-project.org/cgit/beaker/tree/SchemaUpgrades/"&gt;SchemaUpgrades directory&lt;/a&gt; in Beaker’s

https://beaker-project.org/docs/user-guide/contained-test-harness.html
&lt;span class="o"&gt;&amp;lt;&lt;/span&gt;&lt;span class="n"&gt;fetch&lt;/span&gt; &lt;span class="n"&gt;url&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="s2"&gt;&amp;quot;git://git.beaker-project.org/~asaha/restraint_tasks?master#true&amp;quot;&lt;/span&gt;&lt;span class="o"&gt;/&amp;gt;&lt;/span&gt;
&lt;span class="o"&gt;&amp;lt;&lt;/span&gt;&lt;span class="n"&gt;fetch&lt;/span&gt; &lt;span class="n"&gt;url&lt;/span&gt;&lt;span class="o"&gt;=&lt;/span&gt;&lt;span class="s2"&gt;&amp;quot;git://git.beaker-project.org/~asaha/restraint_tasks?master#true&amp;quot;&lt;/span&gt;&lt;span class="o"&gt;/&amp;gt;&lt;/span&gt;

https://beaker-project.org/docs/admin-guide/reporting-queries.html
can &lt;a class="reference external" href="http://git.beaker-project.org/cgit/beaker/tree/Server/bkr/server/reporting-queries"&gt;browse the queries online in Beaker’s

**Comment by duck-rh** [comment]
@StykMartin I removed the RR from the zone.

**Comment by StykMartin** [comment]
@duck-rh We need to drop gerrit.beaker-project.org as well. Other than that good.

**Comment by StykMartin** [comment]
- Zone updated
- Refs removed
