### ISSUE TITLE
IRC is pointing to freenode

### ISSUE THREAD

**Issue by mdujava** [beaker-project/beaker-project.org#40]
https://beaker-project.org/docs/ points to freenode. Should it be updated to irc.libera.chat?

**Comment by p3ck** [comment]
Yes  - can you create a pull request?

**Comment by mdujava** [comment]
You already did :D https://github.com/beaker-project/beaker/commit/d8789d6d2144c16e6cc91f667013ea53d8ad3c49 but its not deployed, @StykMartin can maybe help.

**Comment by p3ck** [comment]
I thought I did!!  but when I saw we had no open pull requests figured it got lost. :-)

**Comment by StykMartin** [comment]
Everything works as expected. The last release was on 21 May 2022. The site hasn't needed to upload new assets since then. I'll have to move CI here. We used Jenkins back then and I'm pretty sure the CI server is dead now.

**Comment by StykMartin** [comment]
The website now points to Libera.
